### ISSUE TITLE
chore: Tailwind config 관련 설정

### ISSUE THREAD

**Issue by VarGun** [KMU-WINK/workinkorea#12]
## 어떤 기능인가요?

> Tailwind CSS 사용을 위한 폰트, 색상 등 디자인 속성 정리

## 작업 상세 내용

- [x] 폰트 세팅
- [ ] config 폰트 사이즈 속성 설정
- [ ] config 색상 속성 설정
- [ ] 사용법 정리 후 공유

## 참고할만한 자료(선택)

**Comment by JisuuungKim** [comment]
폰트 세팅 및 tailwind config에 메인컬러 세팅은 완료했습니다. 
폰트사이즈나 다른 색상의 경우 디자인 측에서 화요일에 정리해준다고 하여 정리본 받고 작업할 예정입니다.
정리본 받고 작업한 후 pr 올려도 될까요?

**Comment by j-myeong** [comment]
@JisuuungKim 진행했던 `tailwind.config.ts` 파일 적용 후, tailwind 기본 컬러가 활성화 되지 않는 오류를 발견하였습니다. 이슈 재오픈하도록 하겠습니다.

**Comment by Choi-Jiwon-38** [comment]
현 시점 tailwind css 관련 이슈 존재하지 않아 close 처리합니다. 발생 시 re-open 해주세요!
