### ISSUE TITLE
feat: Bottom Sheet 작업

### ISSUE THREAD

**Issue by VarGun** [KMU-WINK/workinkorea#14]
## 어떤 기능인가요?

> 소셜 로그인 페이지 Bottom Sheet 개발 작업

## 작업 상세 내용

- [ ] Bottom Sheet 개발
- [ ] 사용법 정리 및 공유

**Comment by j-myeong** [comment]
Bottom sheet가 기획 상에서 사라졌기에, 해당 이슈는 close 하겠습니다.
