### ISSUE TITLE
feat: 전역 상태 관리 라이브러리 세팅

### ISSUE THREAD

**Issue by VarGun** [KMU-WINK/workinkorea#26]

**Comment by VarGun** [comment]
## 어떤 기능인가요?

> 전역 상태 관리를 위한 라이브러리 세팅

## 작업 상세 내용

- [x] 전역으로 관리가 필요한 상태 관련 논의
- [x] Zustand 세팅
- [x] 사용법 정리 후 공유

## 참고할만한 자료(선택)

**Comment by Choi-Jiwon-38** [comment]
Zustand 세팅 및 전역 상태(로그인 유저 정보) 관리 완료되어 이슈 닫도록 하겠습니다~
